import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
   container: {
      flex: 1,
      backgroundColor: '#42A5F5',
      justifyContent: 'center',
      alignItems: 'center',
   },
   rideDriveButtonContent: {
      backgroundColor: '#ffffff',
      height: 250,
      width: 320,
      marginTop: -180,
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
   },
   rideDriveLogoContent: {
      backgroundColor: '#42A5F5',
      height: 900,
      marginTop: -50,
      width: 400,
      borderBottomLeftRadius: 120,
      borderBottomRightRadius: 120,
      justifyContent: 'center',
      alignItems: 'center',
   },
   ButtonContent: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: '#ffffff',
      height: 10,
      width: 320,
      marginTop: 80,
   },
   Ridebutton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#42A5F5',
      height: 50,
      width: 155,
      marginLeft: 13,
   },
   Drivebutton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#ffffff',
      height: 50,
      width: 155,
      borderColor: '#dcdcdc',
      borderWidth: 0.4,
   },
   logo: {
      height: 70,
      width: 70,
      borderRadius: 90,
      marginTop: -100,
   },
});
